'use client';

import { useState } from 'react';
import { FileText, Printer, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { DemoBadge } from '@/components/v2/demo-badge';
import type { DemoCase } from '@/lib/v2/demo-data';
import { caseTypeLabel, formatDate, statusStyles, severityStyles } from '@/lib/v2/format';

function ReportView({ c }: { c: DemoCase }) {
  const status = statusStyles(c.status);
  const severity = severityStyles(c.severity);
  return (
    <div className="rounded-xl border bg-card">
      <div className="flex items-center justify-between border-b p-5 print:hidden">
        <div className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-primary" />
          <h3 className="font-display text-base font-bold tracking-tight">Clinical report</h3>
        </div>
        <div className="flex items-center gap-2">
          <DemoBadge variant="compact" />
          <Button size="sm" variant="outline" onClick={() => window.print()}>
            <Printer className="mr-1.5 h-4 w-4" /> Print / PDF
          </Button>
        </div>
      </div>

      <div className="space-y-6 p-6" id="v2-report">
        <header className="border-b pb-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="font-display text-lg font-bold tracking-tight">Phoenix AI — Wound Assessment Report</p>
              <p className="text-xs text-muted-foreground">Demonstration report · synthetic data · generated {formatDate(new Date().toISOString())}</p>
            </div>
          </div>
        </header>

        <section className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-3">
          <div><p className="text-xs text-muted-foreground">Case reference</p><p className="font-medium">{c.id}</p></div>
          <div><p className="text-xs text-muted-foreground">Alias</p><p className="font-medium">{c.alias}</p></div>
          <div><p className="text-xs text-muted-foreground">Patient</p><p className="font-medium">{c.sex} · {c.ageGroup} yrs</p></div>
          <div><p className="text-xs text-muted-foreground">Clinician</p><p className="font-medium">{c.clinician}</p></div>
          <div><p className="text-xs text-muted-foreground">Facility</p><p className="font-medium">{c.facility}</p></div>
          <div><p className="text-xs text-muted-foreground">Opened</p><p className="font-medium">{formatDate(c.createdAt)}</p></div>
        </section>

        <section>
          <h4 className="mb-2 font-display text-sm font-bold tracking-tight">Assessment</h4>
          <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-3">
            <div><p className="text-xs text-muted-foreground">Type</p><p className="font-medium">{caseTypeLabel(c.caseType)}</p></div>
            <div><p className="text-xs text-muted-foreground">Region</p><p className="font-medium">{c.bodyRegion}</p></div>
            <div><p className="text-xs text-muted-foreground">Mechanism</p><p className="font-medium">{c.mechanism}</p></div>
            {c.tbsaPercent ? <div><p className="text-xs text-muted-foreground">Est. TBSA</p><p className="font-medium">{c.tbsaPercent}%</p></div> : null}
            <div><p className="text-xs text-muted-foreground">Severity</p><p className={cn('font-medium', severity.text)}>{severity.label}</p></div>
            <div><p className="text-xs text-muted-foreground">Status</p><p className={cn('font-medium', status.text)}>{status.label}</p></div>
          </div>
          <p className="mt-3 text-sm text-muted-foreground">{c.summary}</p>
        </section>

        <section>
          <h4 className="mb-2 font-display text-sm font-bold tracking-tight">Management plan</h4>
          <ol className="list-inside list-decimal space-y-1 text-sm text-muted-foreground">
            {c.recommendations.map((r, i) => <li key={i}>{r}</li>)}
          </ol>
        </section>

        <section>
          <h4 className="mb-2 font-display text-sm font-bold tracking-tight">Timeline</h4>
          <ul className="space-y-1 text-sm text-muted-foreground">
            {c.timeline.map((ev) => (
              <li key={ev.id}><span className="font-medium text-foreground">{formatDate(ev.at)}</span> — {ev.title}: {ev.detail}</li>
            ))}
          </ul>
        </section>

        <footer className="border-t pt-4 text-xs text-muted-foreground">
          This is a synthetic demonstration report generated by Phoenix AI v2.0. It contains no real patient data and is not a
          medical record. AI-assisted content is decision-support only and does not replace clinical judgement.
        </footer>
      </div>
    </div>
  );
}

export function ReportsClient({ cases }: { cases: DemoCase[] }) {
  const [selectedId, setSelectedId] = useState<string>(cases[0]?.id ?? '');
  const selected = cases.find((c) => c.id === selectedId) ?? cases[0];

  return (
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-[280px_1fr]">
      <aside className="print:hidden">
        <p className="mb-2 text-sm font-medium text-muted-foreground">Select a case</p>
        <ul className="max-h-[70vh] space-y-1 overflow-y-auto">
          {cases.map((c) => (
            <li key={c.id}>
              <button
                onClick={() => setSelectedId(c.id)}
                className={cn(
                  'flex w-full items-center justify-between rounded-lg border px-3 py-2 text-left text-sm transition-colors hover:bg-muted',
                  c.id === selectedId && 'border-primary/40 bg-primary/5',
                )}
              >
                <span className="min-w-0">
                  <span className="block truncate font-medium">{c.alias}</span>
                  <span className="block truncate text-xs text-muted-foreground">{caseTypeLabel(c.caseType)}</span>
                </span>
                <ChevronRight className="h-4 w-4 shrink-0 text-muted-foreground" />
              </button>
            </li>
          ))}
        </ul>
      </aside>
      {selected ? <ReportView c={selected} /> : null}
    </div>
  );
}
